language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
  include:
    - php: 5.5
      env: COVERAGE=true PHPUNIT_FLAGS="--coverage-clover build/coverage.xml"

before_install:
  - composer self-update

install:
  - composer install

before_script:
  - vendor/bin/http_test_server > /dev/null 2>&1 &

after_success:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi
